apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-database
  namespace: default
spec:
  # Number of instances (1 for dev, 3 for production)
  instances: ${database_instances}
  
  # PostgreSQL image
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6
  
  # Storage configuration
  storage:
    size: ${database_storage_size}
    storageClass: managed-csi  # Azure AKS default storage class
  
  # Bootstrap configuration - creates initial database and user
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
  
  # Resource limits for PostgreSQL pods
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  
  # Monitoring configuration (disabled since Prometheus Operator CRDs are not installed)
  monitoring:
    enablePodMonitor: false
  
  # High availability settings (for production multi-instance)
  primaryUpdateStrategy: unsupervised
  
  # Pod anti-affinity for HA deployments (spreads pods across nodes)
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
  
  # PostgreSQL configuration
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "768MB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "2621kB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
